version: '3.4'

services:
  acc-text-api:
    build:
      context: .
      dockerfile: api/Dockerfile
      cache_from:
        - acctext/api:latest
  gf:
    build:
      context: ./core/gf
      cache_from:
        - acctext/gf:latest
